version: '3.8'
services:
    api:
        build: .
        ports:
            - "8080:3000"
        links:
            - mongo
    mongo:
        image: mongo:6.0.1
        ports:
            - "27017:27017"
        expose:
            - "27017-27019"
        volumes:
            - ./data:/data/db